In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(1,14,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
type(1)

int

In [11]:
type(1.0)

float

In [13]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(1)

array([0.59218925])

In [26]:
np.random.randn(5,4)

array([[ 0.20613561,  0.50415267, -0.45734508, -0.21941078],
       [-1.2863568 ,  0.45048155, -0.62980115, -0.31160315],
       [-0.04057557, -0.27806302,  0.61504555, -0.51890267],
       [ 2.52819505,  1.15565705, -0.44556182,  1.0796612 ],
       [ 1.88871676,  0.0396877 ,  1.40731145, -0.01445149]])

In [30]:
np.random.randint(1,100,5)

array([63,  3, 97, 30, 45])

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([20, 39, 11, 26, 11, 24, 24, 49, 42, 47])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.reshape(25,1).shape

(25, 1)

In [42]:
arr.dtype

dtype('int64')

In [43]:
ranarr.max()

49

In [44]:
ranarr.argmax()

7