In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# broadcast a list

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6] 

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
copy_of_arr = slice_of_arr.copy()

In [18]:
copy_of_arr[:] = 200

In [19]:
copy_of_arr

array([200, 200, 200, 200, 200, 200])

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
mat[0,2]

15

mat[1]

In [26]:
mat[1][2]

30

In [27]:
mat[0][2]

15

In [28]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
mat[:2,0]

array([ 5, 20])

In [30]:
mat:[:2,1:]

SyntaxError: invalid syntax (<ipython-input-30-8a72b545b931>, line 1)

In [31]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 4

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])